// Vue.js/bootstrap-homepage/components/dropZone.vue
<script>
    import { CmsDropZoneComponent } from 'crownpeak-dxm-vuejs-sdk';
    import HeroContainer from "./heroContainer";
    import SecondaryContainer from "./secondaryContainer";

    export default {
        extends: CmsDropZoneComponent,
        name: "DropZone",
        props: ['name'],
        render: function(h) {
            const componentRegistry = {
                "HeroContainer": HeroContainer,
                "SecondaryContainer": SecondaryContainer
            }
            return h('div', { class:'row'}, this.getComponents(h, componentRegistry))
        }
    };
</script>

// React/bootstrap-homepage/components/dropZone.js
import React from 'react';
import { CmsDropZoneComponent } from 'crownpeak-dxm-react-sdk';
import HeroContainer from "./heroContainer";
import SecondaryContainer from "./secondaryContainer";

export default class DropZone extends CmsDropZoneComponent {
    constructor(props)
    {
        super(props);
        this.components = {
            "HeroContainer": HeroContainer,
            "SecondaryContainer": SecondaryContainer
        };
    }

    render() {
        // This method used to override default render() method from SDK, as custom className attribute required.
        return React.createElement('div', { className:'row'},
            this.getComponents()
        );
    }
}
