// Vue.js/bootstrap-homepage/components/heroContainer.vue
<template>
    <div class="container">
        <h1 class="display-3">{{ heading }}</h1>
        <span v-html="description"/>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">{{ button_text }}</a></p>
    </div>
</template>
<script>
    import { CmsComponent, CmsField, CmsFieldTypes } from 'crownpeak-dxm-vuejs-sdk';
    export default {
        extends: CmsComponent,
        name: "HeroContainer",
        data() {
            return {
                heading: new CmsField("Heading", CmsFieldTypes.TEXT, this.$props && this.$props.data ? this.$props.data.Heading : null),
                description: new CmsField("Description", CmsFieldTypes.WYSIWYG, this.$props && this.$props.data ? this.$props.data.Description : null),
                button_text: new CmsField("Button_Text", CmsFieldTypes.TEXT, this.$props && this.$props.data ? this.$props.data.Button_Text : null)
            }
        }
    };
</script>

// React/bootstrap-homepage/components/heroContainer.js
import React from 'react';
import { CmsComponent, CmsField, CmsFieldTypes } from 'crownpeak-dxm-react-sdk';
import ReactHtmlParser from 'react-html-parser';

export default class HeroContainer extends CmsComponent
{
    constructor(props)
    {
        super(props);
        this.heading = new CmsField("Heading", CmsFieldTypes.TEXT, props && props.data ? props.data.Heading : null);
        this.description = new CmsField("Description", CmsFieldTypes.WYSIWYG, props && props.data ? props.data.Description : null);
        this.button_text = new CmsField("Button_Text", CmsFieldTypes.TEXT, props && props.data ? props.data.Button_Text : null);
    }

    render () {
        return (
            <div className="container">
                <h1 className="display-3">{ this.heading }</h1>
                { ReactHtmlParser(this.description) }
                <p><a className="btn btn-primary btn-lg" href="#" role="button">{ this.button_text }</a></p>
            </div>
        )
    }
}
