// Vue.js/bootstrap-homepage/pages/homePage.vue
<template>
    <div>
        <div class="jumbotron">
            <HeroContainer />
        </div>
        <div class="container">
            <div class="row">
                <SecondaryContainer/>
                <SecondaryContainer/>
                <SecondaryContainer/>
            </div>
            <DropZone name="secondary"/>
            <SecondaryListContainer/>
        </div>
        <hr/>
    </div>
</template>
<script>
    import Vue from 'vue';
    import { CmsDynamicPage, CmsStaticPage } from 'crownpeak-dxm-vuejs-sdk';
    import HeroContainer from '../components/heroContainer';
    import SecondaryContainer from '../components/secondaryContainer';
    import DropZone from "../components/dropZone";
    import SecondaryListContainer from "../components/secondaryListContainer";

    Vue.prototype.$cmsAssetId = 266437;

    export default {
        extends: CmsDynamicPage,
        name: "HomePage",
        components: {
            SecondaryListContainer,
            DropZone,
            HeroContainer,
            SecondaryContainer
        }
    };
</script>

// React/bootstrap-homepage/pages/homePage.js
import React from 'react'
import { CmsStaticPage, CmsDynamicPage, CmsDropZoneComponent } from 'crownpeak-dxm-react-sdk';
import DropZone from "../components/dropZone";
import HeroContainer from "../components/heroContainer";
import SecondaryContainer from "../components/secondaryContainer";
import SecondaryListContainer from "../components/secondaryListContainer";

export default class HomePage extends CmsDynamicPage
{
    constructor(props)
    {
        super(props);
        this.cmsAssetId = 266812;
    }

    render() {
        super.render();
        return (
            <div>
                <div className="jumbotron">
                    <HeroContainer />
                </div>
                <div className="container">
                    <div className="row">
                        <SecondaryContainer/>
                        <SecondaryContainer/>
                        <SecondaryContainer/>
                    </div>
                    <DropZone name="secondary"/>
                    <SecondaryListContainer/>
                </div>
                <hr/>
            </div>
        )
    }
}
