// Angular/bootstrap-homepage/pages/homePage.ts
import { Component } from '@angular/core';
import { CmsStaticPage } from 'crownpeak-dxm-angular-sdk';

@Component({
    selector: '[component=HomePage]',
    template: `
            <div class="jumbotron" component="HeroContainer"></div>
            <div class="container">
                <div class="row">
                    <div class="col-md-4" component="SecondaryContainer"></div>
                    <div class="col-md-4" component="SecondaryContainer"></div>
                    <div class="col-md-4" component="SecondaryContainer"></div>
                </div>
                <hr>
                <div class="row" component="SecondaryList"></div>
                <div class="row" component="DropZone" name="secondary"></div>
                <hr>
            </div>
    `
})
export class HomePage extends CmsStaticPage {
    constructor()
    {
        super(null);
        this.cmsAssetId = 270379;
    }

    ngOnInit()
    {
        super.ngOnInit();
    }
}

// React/bootstrap-homepage/pages/homePage.js
import React from 'react'
import { CmsStaticPage, CmsDynamicPage, CmsDropZoneComponent } from 'crownpeak-dxm-react-sdk';
import DropZone from "../components/dropZone";
import HeroContainer from "../components/heroContainer";
import SecondaryContainer from "../components/secondaryContainer";
import SecondaryListContainer from "../components/secondaryListContainer";

export default class HomePage extends CmsDynamicPage
{
    constructor(props)
    {
        super(props);
        this.cmsAssetId = 266812;
    }

    render() {
        super.render();
        return (
            <div>
                <div className="jumbotron">
                    <HeroContainer />
                </div>
                <div className="container">
                    <div className="row">
                        <SecondaryContainer/>
                        <SecondaryContainer/>
                        <SecondaryContainer/>
                    </div>
                    <DropZone name="secondary"/>
                    <SecondaryListContainer/>
                </div>
                <hr/>
            </div>
        )
    }
}
