// React/procam/components/procam/admin/link.js
import React from 'react'
import {CmsComponent, CmsField, CmsFieldTypes} from 'crownpeak-dxm-react-sdk';

export default class Link extends CmsComponent {
    constructor(props) {
        super(props);
        this.title = new CmsField("Title", CmsFieldTypes.TEXT);
        this.url = new CmsField("Url", CmsFieldTypes.HREF);
    }

    render() {
        return (
            <li class="nav-item">
                <a class="nav-link" href={this.url} role="menuitem">{this.title}</a>
            </li>
        )
    }
}

// Angular/procam/components/procam/admin/link.ts
import {Component, Input} from '@angular/core';
import {CmsComponent, CmsField, CmsFieldTypes} from 'crownpeak-dxm-angular-sdk';

// @ts-ignore
@Component({
    selector: '[component=Link]',
    template: `
        <li class="nav-item">
            <a class="nav-link" [href]="url" role="menuitem">{{title}}</a>
        </li>
    `
})
export class Link extends CmsComponent {
    title: CmsField = new CmsField("Title", CmsFieldTypes.TEXT, null);
    url: CmsField = new CmsField("Url", CmsFieldTypes.HREF, null);
}
