// Vue.js/procam/components/imagePanelItem.vue
<template>
  <div class="list-item col-sm-4">
    <figure>
      <img :src="image" :alt="alt"/>
    </figure>
  </div>
</template>
<script>
import {CmsComponent, CmsField, CmsFieldTypes} from 'crownpeak-dxm-vuejs-sdk';

export default {
  extends: CmsComponent,
  name: "ImagePanelItem",
  props: ['data'],
  data() {
    return {
      image: new CmsField("Image", CmsFieldTypes.IMAGE, this.$props && this.$props.data ? this.$props.data.Image : null),
      alt: new CmsField("Alt", CmsFieldTypes.TEXT, this.$props && this.$props.data ? this.$props.data.Alt : null),
    }
  }
};
</script>

// React/procam/components/procam/imagePanelItem.js
import React from 'react'
import {CmsComponent, CmsField, CmsFieldTypes} from 'crownpeak-dxm-react-sdk';

export default class ImagePanelItem extends CmsComponent {
    constructor(props) {
        super(props);
        this.cmsFolder = "Procam";
        this.cmsDisableDragDrop = true;

        this.image = new CmsField("Image", CmsFieldTypes.IMAGE, props && props.data ? props.data.Image : null);
        this.alt = new CmsField("Alt", CmsFieldTypes.TEXT, props && props.data ? props.data.Alt : null);
    }

    render() {
        return (
            <div className="list-item col-sm-4">
                <figure>
                    <img src={this.image} alt={this.alt}/>
                </figure>
            </div>
        )
    }
}
