// Angular/procam/components/procam/products.ts
import {Component, Input} from '@angular/core';
import {CmsComponent, CmsField, CmsFieldTypes} from 'crownpeak-dxm-angular-sdk';

@Component({
    selector: '[component=Products]',
    template: `
        <section class="full-width listing bg-grey angle--top-right">
            <div class="container-fluid">
                <h2 class="sectionHead">{{title}}</h2>
                <div class="row text-center">
                    <!-- cp-scaffold
                        <cp-list name="Products">
                            <div class="list-item col-sm-6 col-lg-3">
                                {ProductItem:ProductItem}
                            </div>
                        </cp-list>
                        else -->
                    <div component="ProductItem" class="list-item col-sm-6 col-lg-3" *ngFor="let sc of products.value"
                         [data]="sc.ProductItem"></div>
                    <!-- /cp-scaffold -->
                </div>
            </div>
        </section>
    `
})
export class Products extends CmsComponent {
    @Input() data: any;
    title: CmsField = new CmsField("Title", CmsFieldTypes.TEXT, null);
    products: CmsField = new CmsField("Products", "ProductItem", null);
}

// React/procam/components/procam/products.js
import React from 'react'
import {CmsComponent, CmsDataCache, CmsField, CmsFieldTypes} from 'crownpeak-dxm-react-sdk';
import ProductItem from "./productItem";

export default class Products extends CmsComponent {
    constructor(props) {
        super(props);
        this.title = new CmsField("Title", CmsFieldTypes.TEXT, props && props.data ? props.data.Title : null);
        this.products = new CmsField("Products", "", CmsDataCache.get(CmsDataCache.cmsAssetId).Products.Products|| []);
    }

    render() {
        let i = 0;
        return (
            <div className="cp-component-div">
                <section className="full-width listing bg-grey angle--top-right">
                    <div className="container-fluid">
                        <h2 className="sectionHead">{this.title}</h2>
                        <div className="row text-center">
                            {/* <List name="Products" type="ProductItem"> */}
                            {this.products.value.map(sc => {
                                return <ProductItem data={sc.ProductItem} key={i++}/>
                            })}
                            {/* </List> */}
                        </div>
                    </div>
                </section>
            </div>
        )
    }
}
