// Vue.js/procam/components/productItem.vue
<template>
  <div class="list-item col-sm-6 col-lg-3">
    <a :href="link">
      <img :src="image" :alt="alt" style="max-width:252px"/>
    </a>
    <h4>{{title}}</h4>
    <div class="button-group">
      <a class="btn btn-small btn-light-blue" :href="link">{{cta_text}}</a>
    </div>
  </div>
</template>
<script>
import {CmsComponent, CmsField, CmsFieldTypes} from 'crownpeak-dxm-vuejs-sdk';

export default {
  extends: CmsComponent,
  name: "ProductItem",
  props: ['data'],
  data() {
    return {
      link: new CmsField("Link", CmsFieldTypes.HREF, this.$props && this.$props.data ? this.$props.data.Link : null),
      image: new CmsField("Image", CmsFieldTypes.IMAGE, this.$props && this.$props.data ? this.$props.data.Image : null),
      alt: new CmsField("Alt", CmsFieldTypes.TEXT, this.$props && this.$props.data ? this.$props.data.Alt : null),
      title: new CmsField("Title", CmsFieldTypes.TEXT, this.$props && this.$props.data ? this.$props.data.Title : null),
      cta_text: new CmsField("CTA_Text", CmsFieldTypes.TEXT, this.$props && this.$props.data ? this.$props.data.CTA_Text : null),
    }
  }
};
</script>

// React/procam/components/procam/productItem.js
import React from 'react'
import {CmsComponent, CmsField, CmsFieldTypes} from 'crownpeak-dxm-react-sdk';

export default class ProductItem extends CmsComponent {
    constructor(props) {
        super(props);
        this.link = new CmsField("Link", CmsFieldTypes.HREF, props && props.data ? props.data.Link : null);
        this.image = new CmsField("Image", CmsFieldTypes.IMAGE, props && props.data ? props.data.Image : null);
        this.alt = new CmsField("Alt", CmsFieldTypes.TEXT, props && props.data ? props.data.Alt : null);
        this.title = new CmsField("Title", CmsFieldTypes.TEXT, props && props.data ? props.data.Title : null);
        this.cta_text = new CmsField("CTA_Text", CmsFieldTypes.TEXT, props && props.data ? props.data.CTA_Text : null);
    }

    render() {
        return (
            <div className="list-item col-sm-6 col-lg-3">
                <a href={this.link}>
                    <img src={this.image} alt={this.alt} style={{maxWidth:'252px'}}/>
                </a>
                <h4>{this.title}</h4>
                <div className="button-group">
                    <a className="btn btn-small btn-light-blue" href={this.link}>{this.cta_text}</a>
                </div>
            </div>
        )
    }
}
