// Vue.js/procam/components/procam/products.vue
<template>
  <div class="cp-component-div">
    <section class="full-width listing bg-grey angle--top-right">
      <div class="container-fluid">
        <h2 class="sectionHead">{{title}}</h2>
        <div class="row text-center">
          <!-- <List name="Products" type="ProductItem"> -->
          <ProductItem v-for="(sc, i) in products.value" :key="i" v-bind:data="sc.ProductItem" />
          <!-- </List> -->
        </div>
      </div>
    </section>
  </div>
</template>
<script>
import {CmsComponent, CmsDataCache, CmsField, CmsFieldTypes} from 'crownpeak-dxm-vuejs-sdk';
import ProductItem from "./productItem.vue";

export default {
  extends: CmsComponent,
  name: "Products",
  components: {
    ProductItem
  },
  data() {
    return {
      title: new CmsField("Title", CmsFieldTypes.TEXT, this.$props && this.$props.data ? this.$props.data.Title : null),
      products: new CmsField("Products", "ImagePanelItem", CmsDataCache.get(CmsDataCache.cmsAssetId).Products.Products || []),
    }
  }
};
</script>

// React/procam/components/procam/products.js
import React from 'react'
import {CmsComponent, CmsDataCache, CmsField, CmsFieldTypes} from 'crownpeak-dxm-react-sdk';
import ProductItem from "./productItem";

export default class Products extends CmsComponent {
    constructor(props) {
        super(props);
        this.title = new CmsField("Title", CmsFieldTypes.TEXT, props && props.data ? props.data.Title : null);
        this.products = new CmsField("Products", "", CmsDataCache.get(CmsDataCache.cmsAssetId).Products.Products|| []);
    }

    render() {
        let i = 0;
        return (
            <div className="cp-component-div">
                <section className="full-width listing bg-grey angle--top-right">
                    <div className="container-fluid">
                        <h2 className="sectionHead">{this.title}</h2>
                        <div className="row text-center">
                            {/* <List name="Products" type="ProductItem"> */}
                            {this.products.value.map(sc => {
                                return <ProductItem data={sc.ProductItem} key={i++}/>
                            })}
                            {/* </List> */}
                        </div>
                    </div>
                </section>
            </div>
        )
    }
}
