// React/bootstrap-homepage/components/secondaryContainer.js
import React from 'react';
import {CmsComponent, CmsField, CmsFieldTypes } from 'crownpeak-dxm-react-sdk';
import ReactHtmlParser from "react-html-parser";

export default class SecondaryContainer extends CmsComponent
{
    constructor(props)
    {
        super(props);
        this.heading = new CmsField("Heading", CmsFieldTypes.TEXT, props && props.data ? props.data.Heading : null);
        this.description = new CmsField("Description", CmsFieldTypes.WYSIWYG, props && props.data ? props.data.Description : null);
        this.button_text = new CmsField("Button_Text", CmsFieldTypes.TEXT, props && props.data ? props.data.Button_Text : null);
    }

    render () {
        return (
            <div className="col-md-4">
                <h2>{ this.heading }</h2>
                { ReactHtmlParser(this.description) }
                <p><a className="btn btn-secondary" href="#" role="button">{ this.button_text }</a></p>
            </div>
        )
    }
}

// Vue.js/bootstrap-homepage/components/secondaryContainer.vue
<template>
    <div class="col-md-4">
        <h2>{{ heading }}</h2>
        <span v-html="description"/>
        <p><a class="btn btn-secondary" href="#" role="button">{{ button_text }}</a></p>
    </div>
</template>
<script>
    import { CmsComponent, CmsField, CmsFieldTypes } from 'crownpeak-dxm-vuejs-sdk';
    export default {
        extends: CmsComponent,
        name: "SecondaryContainer",
        props: ['data'],
        data() {
            return {
                heading: new CmsField("Heading", CmsFieldTypes.TEXT, this.$props && this.$props.data ? this.$props.data.Heading : null),
                description: new CmsField("Description", CmsFieldTypes.WYSIWYG, this.$props && this.$props.data ? this.$props.data.Description : null),
                button_text: new CmsField("Button_Text", CmsFieldTypes.TEXT, this.$props && this.$props.data ? this.$props.data.Button_Text : null)
            }
        }
    };
</script>
