// React/bootstrap-homepage/components/secondaryListContainer.js
import React from 'react';
import {CmsComponent, CmsField } from 'crownpeak-dxm-react-sdk';
import SecondaryContainer from "./secondaryContainer";

export default class SecondaryListContainer extends CmsComponent
{
    constructor(props)
    {
        super(props);
        this.SecondaryContainers = new CmsField("SecondaryContainer", "", window.cmsDataCache[window.cmsDataCache.cmsAssetId].SecondaryListContainer);
    }

    render () {
        let i = 0;
        return (
            <div className="row">
                {/* <List name="SecondaryContainers" type="SecondaryContainer"> */}
                {this.SecondaryContainers.value.map(sc => {
                    return <SecondaryContainer data={sc.SecondaryContainer} key={i++}/>
                })}
                {/* </List> */}
            </div>
        )
    }
}

// Vue.js/bootstrap-homepage/components/secondaryListContainer.vue
<template>
    <div class="row">
        <!-- <List name="SecondaryContainers" type="SecondaryContainer"> -->
        <SecondaryContainer v-for="(sc, i) in secondaryContainers.value" :key="i" v-bind:data="sc.SecondaryContainer" />
        <!-- </List> -->
    </div>
</template>
<script>
    import { CmsComponent, CmsField } from 'crownpeak-dxm-vuejs-sdk';
    import SecondaryContainer from './secondaryContainer';
    export default {
        extends: CmsComponent,
        name: "SecondaryListContainer",
        props: ['data'],
        data() {
            return {
                secondaryContainers: new CmsField("SecondaryContainer", "", window.cmsDataCache[window.cmsDataCache.cmsAssetId].SecondaryListContainer)
            }
        },
        components: {
            SecondaryContainer
        }
    };
</script>
