// Vue.js/procam/components/imagePanelItem.vue
<template>
  <div class="list-item col-sm-4">
    <figure>
      <img :src="image" :alt="alt"/>
    </figure>
  </div>
</template>
<script>
import {CmsComponent, CmsField, CmsFieldTypes} from 'crownpeak-dxm-vuejs-sdk';

export default {
  extends: CmsComponent,
  name: "ImagePanelItem",
  props: ['data'],
  data() {
    return {
      image: new CmsField("Image", CmsFieldTypes.IMAGE, this.$props && this.$props.data ? this.$props.data.Image : null),
      alt: new CmsField("Alt", CmsFieldTypes.TEXT, this.$props && this.$props.data ? this.$props.data.Alt : null),
    }
  }
};
</script>

// React/Procam-Gatsby/src/components/raw/imagePanelItem.js
import * as React from "react"
import { CmsDataCache, CmsField, CmsFieldTypes } from 'crownpeak-dxm-react-sdk'

const ImagePanelItem = (props) => {
    CmsDataCache.setComponent("ImagePanelItem");
    const cmsDisableDragDrop = true;

    let image = new CmsField("Image", CmsFieldTypes.IMAGE, props && props.data ? props.data.Image : null);
    let alt = new CmsField("Alt", CmsFieldTypes.TEXT, props && props.data ? props.data.Alt : null);

    return (
        <div className="list-item col-sm-4">
            <figure>
                <img src={image} alt={alt} />
            </figure>
        </div>
    )
}

export default ImagePanelItem
