// Vue.js/bootstrap-blog/components/featuredPost.vue
<template>
    <div class="col-md-6 px-0">
        <h1 class="display-4 font-italic">{{ post_title }}</h1>
        <p class="lead my-3" v-html="post_leader"></p>
        <p class="lead mb-0"><a href="#" class="text-white font-weight-bold">Continue
            reading...</a></p>
    </div>
</template>
<script>
    import { CmsComponent, CmsField, CmsFieldTypes } from 'crownpeak-dxm-vuejs-sdk';
    export default {
        extends: CmsComponent,
        name: "FeaturedPost",
        data() {
            return {
                post_title: new CmsField("Post_Title", CmsFieldTypes.TEXT, this.$props && this.$props.data ? this.$props.data.Post_Title : null),
                post_leader: new CmsField("Post_Leader", CmsFieldTypes.WYSIWYG, this.$props && this.$props.data ? this.$props.data.Post_Leader : null)
            }
        }
    };
</script>

// React/procam/components/blog/featuredPost.js
import React from 'react';
import { CmsComponent, CmsField, CmsFieldTypes } from 'crownpeak-dxm-react-sdk';
import ReactHtmlParser from 'react-html-parser';

export default class FeaturedPost extends CmsComponent
{
    constructor(props)
    {
        super(props);
        this.post_title = new CmsField("Post_Title", CmsFieldTypes.TEXT);
        this.post_leader = new CmsField("Post_Leader", CmsFieldTypes.WYSIWYG);
    }

    render() {
        return (
            <div className="col-md-6 px-0">
                <h1 className="display-4 font-italic">{ this.post_title }</h1>
                <div className="lead my-3">{ ReactHtmlParser(this.post_leader) }</div>
                <p className="lead mb-0"><a href="#" className="text-white font-weight-bold">Continue
                    reading...</a></p>
            </div>
        )
    }
}
