// Vue.js/procam/components/blog/secondaryPost.vue
<template>
    <div class="card flex-md-row mb-4 box-shadow h-md-250">
        <div class="card-body d-flex flex-column align-items-start">
            <strong class="d-inline-block mb-2 text-primary">World</strong>
            <h3 class="mb-0">
                <a class="text-dark" href="#">{{ post_title }}</a>
            </h3>
            <div class="mb-1 text-muted">{{ new Date(post_date).toLocaleDateString() }}</div>
            <p class="card-text mb-auto" v-html="post_content"></p>
            <a href="#">Continue reading</a>
        </div>
        <img class="card-img-right flex-auto d-none d-md-block"
                data-src="holder.js/200x250?theme=thumb" alt="Card image cap" />
    </div>
</template>
<script>
    import { CmsComponent, CmsField, CmsFieldTypes } from 'crownpeak-dxm-vuejs-sdk';
    export default {
        extends: CmsComponent,
        name: "SecondaryPost",
        data() {
            return {
                post_title: new CmsField("Post_Title", CmsFieldTypes.TEXT, this.$props && this.$props.data ? this.$props.data.Post_Title : null),
                post_date: new CmsField("Post_Date", CmsFieldTypes.DATE, this.$props && this.$props.data ? this.$props.data.Post_Date : null),
                post_content: new CmsField("Post_Content", CmsFieldTypes.WYSIWYG, this.$props && this.$props.data ? this.$props.data.Post_Content : null)
            }
        }
    };
</script>

// React/procam/components/blog/secondaryPost.js
import React from 'react';
import { CmsComponent, CmsField, CmsFieldTypes } from 'crownpeak-dxm-react-sdk';
import ReactHtmlParser from 'react-html-parser';

export default class SecondaryPost extends CmsComponent
{
    constructor(props)
    {
        super(props);
        this.cmsFolder = "Blogs";
        this.cmsDisableDragDrop = true;

        this.post_title = new CmsField("Post_Title", CmsFieldTypes.TEXT);
        this.post_date = new CmsField("Post_Date", CmsFieldTypes.DATE);
    }

    render() {
        return (
                <div className="card flex-md-row mb-4 box-shadow h-md-250">
                    <div className="card-body d-flex flex-column align-items-start">
                        <strong className="d-inline-block mb-2 text-primary">World</strong>
                        <h3 className="mb-0">
                            <a className="text-dark" href="#">{ this.post_title }</a>
                        </h3>
                        <div className="mb-1 text-muted">{ new Date(this.post_date).toLocaleDateString() }</div>
                        <div className="card-text mb-auto">{ ReactHtmlParser(new CmsField("Post_Content", CmsFieldTypes.WYSIWYG)) }</div>
                        <a href="#">Continue reading</a>
                    </div>
                    <img className="card-img-right flex-auto d-none d-md-block"
                         data-src="holder.js/200x250?theme=thumb" alt="Card image cap" />
                </div>
        )
    }
}
