// React/Procam-Gatsby/src/components/draggable/imagePanel.js
import * as React from "react"
import { CmsDataCache, CmsField, CmsFieldTypes } from 'crownpeak-dxm-react-sdk'
import ImagePanelItem from '../raw/imagePanelItem'

const ImagePanel = (props) => {
    CmsDataCache.setComponent("ImagePanel");
    const cmsDisableDragDrop = false;

    let title = new CmsField("Title", CmsFieldTypes.TEXT, props && props.data ? props.data.Title : null);
    let right_image = new CmsField("Right_Image", CmsFieldTypes.IMAGE, props && props.data ? props.data.Right_Image : null);
    let right_image_alt = new CmsField("Right_Image_Alt", CmsFieldTypes.TEXT, props && props.data ? props.data.Right_Image_Alt : null);
    let images = new CmsField("Images", "ImagePanelItem", (CmsFieldTypes.TEXT, props && props.data ? props.data.Images : CmsDataCache.get(CmsDataCache.cmsAssetId)[CmsDataCache.cmsComponentName].Images) || []);
    let i = 0;
    return (
        <div className="cp-component-div">
            <section
                className="full-width listing bg-image bg-bar-bottom  bg-bar-white angle--top-left">
                <div className="container-fluid">
                    <div className="sectionHead row align-items-center">
                        <div className="col">
                            <h2>{title}</h2>
                        </div>
                        <div className="col-auto">
                            <img src={right_image} alt={right_image_alt} />
                        </div>
                    </div>
                    <div className="row">
                        {/* <List name="Images" type="ImagePanelItem"> */}
                        {images.map(sc => {
                            return <ImagePanelItem data={sc.ImagePanelItem} key={i++}/>
                        })}
                        {/* </List> */}
                    </div>
                </div>
            </section>
        </div>
    )
}

export default ImagePanel

// Vue.js/procam/components/procam/imagePanel.vue
<template>
  <div class="cp-component-div">
    <section
        class="full-width listing bg-image bg-bar-bottom  bg-bar-white angle--top-left">
      <div class="container-fluid">
        <div class="sectionHead row align-items-center">
          <div class="col">
            <h2>{{title}}</h2>
          </div>
          <div class="col-auto">
            <img :src="right_image" :alt="right_image_alt"/>
          </div>
        </div>
        <div class="row">
          <!-- <List name="Images" type="ImagePanelItem"> -->
          <ImagePanelItem v-for="(sc, i) in images.value" :key="i" v-bind:data="sc.ImagePanelItem" />
          <!-- </List> -->
        </div>
      </div>
    </section>
  </div>
</template>
<script>
import {CmsComponent, CmsDataCache, CmsField, CmsFieldTypes} from 'crownpeak-dxm-vuejs-sdk';
import ImagePanelItem from "./imagePanelItem.vue";

export default {
  extends: CmsComponent,
  name: "ImagePanel",
  components: {
    ImagePanelItem
  },
  data() {
    return {
      title: new CmsField("Title", CmsFieldTypes.TEXT, this.$props && this.$props.data ? this.$props.data.Title : null),
      right_image: new CmsField("Right_Image", CmsFieldTypes.IMAGE, this.$props && this.$props.data ? this.$props.data.Right_Image : null),
      right_image_alt: new CmsField("Right_Image_Alt", CmsFieldTypes.TEXT, this.$props && this.$props.data ? this.$props.data.Right_Image_Alt : null),
      images: new CmsField("Images", "ImagePanelItem", CmsDataCache.get(CmsDataCache.cmsAssetId).ImagePanel.Images || []),
    }
  }
};
</script>
