// React/Procam-Gatsby/src/components/draggable/products.js
import * as React from "react"
import { CmsDataCache, CmsField, CmsFieldTypes } from 'crownpeak-dxm-react-sdk'
import ProductItem from '../raw/productItem'

const Products = (props) => {
    CmsDataCache.setComponent("Products");
    const cmsDisableDragDrop = false;

    let title = new CmsField("Title", CmsFieldTypes.TEXT, props && props.data ? props.data.Title : null);
    let products = new CmsField("Products", "ProductItem", (CmsFieldTypes.TEXT, props && props.data ? props.data.Products : CmsDataCache.get(CmsDataCache.cmsAssetId)[CmsDataCache.cmsComponentName].Products) || []);
    let i = 0;

    return (
        <div className="cp-component-div">
                <section className="full-width listing bg-grey angle--top-right">
                    <div className="container-fluid">
                        <h2 className="sectionHead">{title}</h2>
                        <div className="row text-center">
                            {/* <List name="Products" type="ProductItem"> */}
                            {products.map(sc => {
                                return <ProductItem data={sc.ProductItem} key={i++}/>
                            })}
                            {/* </List> */}
                        </div>
                    </div>
                </section>
            </div>
    )
}

export default Products

// Vue.js/procam/components/procam/products.vue
<template>
  <div class="cp-component-div">
    <section class="full-width listing bg-grey angle--top-right">
      <div class="container-fluid">
        <h2 class="sectionHead">{{title}}</h2>
        <div class="row text-center">
          <!-- <List name="Products" type="ProductItem"> -->
          <ProductItem v-for="(sc, i) in products.value" :key="i" v-bind:data="sc.ProductItem" />
          <!-- </List> -->
        </div>
      </div>
    </section>
  </div>
</template>
<script>
import {CmsComponent, CmsDataCache, CmsField, CmsFieldTypes} from 'crownpeak-dxm-vuejs-sdk';
import ProductItem from "./productItem.vue";

export default {
  extends: CmsComponent,
  name: "Products",
  components: {
    ProductItem
  },
  data() {
    return {
      title: new CmsField("Title", CmsFieldTypes.TEXT, this.$props && this.$props.data ? this.$props.data.Title : null),
      products: new CmsField("Products", "ImagePanelItem", CmsDataCache.get(CmsDataCache.cmsAssetId).Products.Products || []),
    }
  }
};
</script>
