// React/procam/components/blog/monthHeader.js
import React from 'react';
import { CmsComponent } from 'crownpeak-dxm-react-sdk';

export default class MonthHeader extends CmsComponent
{
    render() {
        return (
            <div className="col-4 text-center">
                <a className="blog-header-logo text-dark" href="#">
                    {/* cp-scaffold
                        Current Month
                    else */}
                        {this.props.month}
                    {/* /cp-scaffold */}
                </a>
            </div>
        )
    }
}

// Angular/procam/components/blog/monthHeader.ts
import {Component, Input} from '@angular/core';
import {CmsComponent} from 'crownpeak-dxm-angular-sdk';

// @ts-ignore
@Component({
    selector: '[component=MonthHeader]',
    template: `
        <a class="blog-header-logo text-dark" href="#">
            <!-- cp-scaffold
                Current Month
            else -->
            {{month}}
            <!-- /cp-scaffold -->
        </a>
    `
})
export class MonthHeader extends CmsComponent {
    // @ts-ignore
    @Input() month: any;
}
