// Vue.js/procam/components/blog/topicList.vue
<template>
    <div class="nav-scroller py-1 mb-2">
        <nav class="nav d-flex justify-content-between">
          <!-- cp-scaffold
            Topic List
          else -->
          <a v-for="topic in topics" :key="topic" class="p-2 text-muted" href="#">{{ topic }}</a>
          <!-- /cp-scaffold -->
        </nav>
    </div>
</template>
<script>
    import { CmsComponent, CmsStaticDataProvider } from 'crownpeak-dxm-vuejs-sdk';
    export default {
        extends: CmsComponent,
        name: "TopicList",
        data() {
            return {
                topics: new CmsStaticDataProvider().getCustomDataSync("topics.json")
            }
        }
    };
</script>

// Angular/procam/components/blog/topicList.ts
import {Component, Input} from '@angular/core';
import {CmsComponent, CmsStaticDataProvider} from 'crownpeak-dxm-angular-sdk';

// @ts-ignore
@Component({
    selector: '[component=TopicList]',
    template: `
        <nav class="nav d-flex justify-content-between">
            <!-- cp-scaffold
                    Topics
            else -->
                <a *ngFor="let topic of topics" class="p-2 text-muted" href="#">{{ topic }}</a>
            <!-- /cp-scaffold -->
        </nav>
    `
})
export class TopicList extends CmsComponent {
    // @ts-ignore
    @Input() data: any;
    topics: {} = new CmsStaticDataProvider().getCustomDataSync("topics.json");
}
