// Vue.js/procam/components/procam/admin/headerNavigationAdmin.vue
<template>
  <div class="navbar-collapse collapse" id="navigationContent">
    <ul class="navbar-nav" role="menubar">
      <!-- <List name="NavItems" type="Link"> -->
      <li class="nav-item" v-for="(sc, i) in nav_items.value" :key="i">
        <a class="nav-link" href="{sc.Link.url}" role="menuitem">{sc.Link.title}</a>
      </li>
      <!-- </List> -->
    </ul>
  </div>
</template>
<script>
import {CmsComponent, CmsField} from 'crownpeak-dxm-vuejs-sdk';

export default {
  extends: CmsComponent,
  name: "HeaderNavigationAdmin",
  data() {
    return {
      nav_items: new CmsField("Nav_Items", "", CmsDataCache.get(CmsDataCache.cmsAssetId).Nav_Items.Links || [])
    }
  }
};
</script>

// React/Procam-Gatsby/src/components/admin/headerNavigationAdmin.js
import * as React from "react"
import { CmsDataCache, CmsField, CmsFieldTypes } from 'crownpeak-dxm-react-sdk'

const HeaderNavigationAdmin = (props) => {
    CmsDataCache.setComponent("HeaderNavigationAdmin");
    const cmsDisableDragDrop = true;
    let nav_items = new CmsField("Nav_Items", "ProductItem", (CmsFieldTypes.TEXT, props && props.data ? props.data.Products : CmsDataCache.get(CmsDataCache.cmsAssetId)[CmsDataCache.cmsComponentName].Nav_Items) || []);

    return (
        <div className="navbar-collapse collapse" id="navigationContent">
            <ul className="navbar-nav" role="menubar">
                {/* <List name="NavItems" type="Link"> */}
                {nav_items.value.map(item => {
                    return
                    <li className="nav-item" key={i++}>
                        <a className="nav-link" href="{item.NavItem.url}" role="menuitem">{item.NavItem.title}</a>
                    </li>
                })}
                {/* </List> */}
            </ul>
        </div>
    )
}

export default HeaderNavigationAdmin
