// React/Procam-Gatsby/src/components/global/headerNavigation.js
import * as React from "react"
import { CmsDataCache } from 'crownpeak-dxm-react-sdk'

const HeaderNavigation = (props) => {
    CmsDataCache.setComponent("HeaderNavigation");
    const cmsDisableDragDrop = false;

    let i = 0;
    return (
        <div className="navbar-collapse collapse" id="navigationContent">
            <ul className="navbar-nav" role="menubar">
                {/* cp-scaffold
                    {headerNavigationPreview:HeaderNavigationPreview}
                else */}
                    {props.data.map((item) => {
                        return <li className="nav-item" key={i++}>
                            <a className="nav-link" href={item.Link.Url} role="menuitem">{item.Link.Title}</a>
                        </li>
                    })}
                {/* /cp-scaffold */}
            </ul>
        </div>
    )
}

export default HeaderNavigation

// Vue.js/procam/components/procam/global/headerNavigation.vue
<template>
  <div class="navbar-collapse collapse" id="navigationContent">
    <ul class="navbar-nav" role="menubar">
      <!-- cp-scaffold
        {headerNavigationPreview:HeaderNavigationPreview}
      else -->
        <li class="nav-item" v-for="(item, i) in nav_items" :key="i">
          <a class="nav-link" :href="item.Link.Url" role="menuitem">{{item.Link.title}}</a>
        </li>
      <!-- /cp-scaffold -->
    </ul>
  </div>
</template>
<script>
import {CmsComponent,CmsStaticDataProvider, CmsDynamicDataProvider} from 'crownpeak-dxm-vuejs-sdk';

export default {
  extends: CmsComponent,
  name: "HeaderNavigation",
  props: ['dataProvider'],
  data() {
    return {
      nav_items: []
    }
  },
  mounted() {
    if(this.$props.dataProvider instanceof CmsStaticDataProvider)
      this.nav_items = new CmsStaticDataProvider().getCustomDataSync("284119.json").HeaderNavigationAdmin.NavItems;
    else if (this.$props.dataProvider instanceof CmsDynamicDataProvider)
      this.nav_items = new CmsDynamicDataProvider().getDynamicQuerySync("q=284119&fl=custom_t_json:[json]").response.docs[0].custom_t_json.HeaderNavigationAdmin.NavItems;
  }
};
</script>
