// React/Procam-Gatsby/src/templates/admin.js
import * as React from "react"
import { CmsDataCache } from 'crownpeak-dxm-react-sdk'
import HeaderNavigationAdmin from "../components/admin/headerNavigationAdmin"

const Admin = ({ data, pageContext }) => {
  // CmsPage
  CmsDataCache.cmsAssetId = pageContext.assetId;
  CmsDataCache.set(CmsDataCache.cmsAssetId, data.homePage);
  return (
    <HeaderNavigationAdmin/>
  )
}

export default Admin;

// Vue.js/procam/pages/admin.vue
<template>
    <HeaderNavigationAdmin v-if="isLoaded" />
</template>
<script>
import {CmsDynamicPage} from 'crownpeak-dxm-vuejs-sdk';
import HeaderNavigationAdmin from "../components/procam/admin/headerNavigationAdmin";

export default {
  extends: CmsDynamicPage,
  name: "Admin",
  components: {
    HeaderNavigationAdmin
  },
  cmsWrapper: "ProCam",
  cmsUseTmf: false,
  cmsSuppressModel: true,
  cmsSuppressFolder: true
};
</script>
