// Vue.js/bootstrap-homepage/components/heroContainer.vue
<template>
    <div class="container">
        <h1 class="display-3">{{ heading }}</h1>
        <span v-html="description"/>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">{{ button_text }}</a></p>
    </div>
</template>
<script>
    import { CmsComponent, CmsField, CmsFieldTypes } from 'crownpeak-dxm-vuejs-sdk';
    export default {
        extends: CmsComponent,
        name: "HeroContainer",
        data() {
            return {
                heading: new CmsField("Heading", CmsFieldTypes.TEXT, this.$props && this.$props.data ? this.$props.data.Heading : null),
                description: new CmsField("Description", CmsFieldTypes.WYSIWYG, this.$props && this.$props.data ? this.$props.data.Description : null),
                button_text: new CmsField("Button_Text", CmsFieldTypes.TEXT, this.$props && this.$props.data ? this.$props.data.Button_Text : null)
            }
        }
    };
</script>

// Angular/bootstrap-homepage/components/heroContainer.ts
import {Component, Input} from '@angular/core';
import { CmsComponent, CmsField, CmsFieldTypes } from 'crownpeak-dxm-angular-sdk';

@Component({
    selector: '[component=HeroContainer]',
    template: `
        <div class="container">
            <h1 class="display-3">{{ heading }}</h1>
            <div [innerHTML]="description"></div>
            <p><a class="btn btn-primary btn-lg" href="#" role="button">{{ button_text }}</a></p>
        </div>
    `
})
export class HeroContainer extends CmsComponent {
    @Input() data:any;
    heading: CmsField = new CmsField("Heading", CmsFieldTypes.TEXT, null);
    description: CmsField = new CmsField("Description", CmsFieldTypes.WYSIWYG, null);
    button_text: CmsField = new CmsField("Button_Text", CmsFieldTypes.TEXT, null);
}
