// Angular/procam/pages/admin.ts
import {Component} from '@angular/core';
import {CmsDynamicPage} from 'crownpeak-dxm-angular-sdk';
import {ActivatedRoute} from "@angular/router";

// @ts-ignore
@Component({
    template: `
        <div component="HeaderNavigationAdmin" *ngIf="isLoaded"></div>
    `
})
export class Admin extends CmsDynamicPage {
    constructor(private route: ActivatedRoute) {
        super(null);
        this.cmsWrapper = "ProCam";
        this.cmsUseTmf = false;
        this.cmsSuppressModel = true;
        this.cmsSuppressFolder = true;
    }

    ngOnInit() {
        this.cmsAssetId = this.route.snapshot.data.cmsassetid;
        super.ngOnInit();
    }
}

// React/procam/pages/admin.js
import React from 'react'
import { CmsDynamicPage, CmsStaticPage } from 'crownpeak-dxm-react-sdk';
import Routing from "../core/routing";
import HeaderNavigationAdmin from "../components/procam/admin/headerNavigationAdmin";

export default class Admin extends CmsDynamicPage
{
    constructor(props)
    {
        super(props);
        this.cmsSuppressFolder = true;
        this.cmsUseTmf = false;
        this.cmsWrapper = "ProCam";
        if(this.props && this.props.location) this.cmsAssetId = Routing.getCmsAssetId(this.props.location.pathname);
    }

    render() {
        super.render();
        return (
            this.state.isLoaded &&
            <HeaderNavigationAdmin/>
        )
    }
}
