// React/procam/components/imagePanelItemList.js
import React from 'react'
import {CmsComponent, CmsField, CmsFieldTypes, CmsDataCache} from 'crownpeak-dxm-react-sdk';
import ImagePanelItem from "./imagePanelItem";

export default class ImagePanelItemList extends CmsComponent {
    constructor(props) {
        super(props);
        this.images = new CmsField("Images", "ImagePanelItem", CmsDataCache.get(CmsDataCache.cmsAssetId).ImagePanel.ImagePanelItemList || []);
    }

    render() {
        let i = 0;
        return (
            <div className="row">
                {/* <List name="Images" type="ImagePanelItem"> */}
                {this.images.value.map(sc => {
                    return <ImagePanelItem data={sc.ImagePanelItem} key={i++}/>
                })}
                {/* </List> */}
            </div>

        )
    }
}

// Vue.js/procam/components/imagePanelItemList.vue
<template>
  <div class="row">
    <!-- <List name="Images" type="ImagePanelItem"> -->
    <ImagePanelItem v-for="(sc, i) in images.value" :key="i" v-bind:data="sc.ImagePanelItem" />
    <!-- </List> -->
  </div>
</template>
<script>
import {CmsComponent, CmsField, CmsDataCache} from 'crownpeak-dxm-vuejs-sdk';
import ImagePanelItem from "../components/imagePanelItem.vue";

export default {
  extends: CmsComponent,
  name: "ImagePanelItemList",
  props: ['data'],
  components: {
    ImagePanelItem
  },
  data() {
    return {
      images: new CmsField("Images", "ImagePanelItem", CmsDataCache.get(CmsDataCache.cmsAssetId).ImagePanel.ImagePanelItemList || []),
    }
  }
};
</script>
