// React/procam/components/products.js
import React from 'react'
import {CmsComponent, CmsDataCache, CmsField, CmsFieldTypes} from 'crownpeak-dxm-react-sdk';
import ProductItemList from "./productItemList";

export default class Products extends CmsComponent {
    constructor(props) {
        super(props);
        this.title = new CmsField("Title", CmsFieldTypes.TEXT, props && props.data ? props.data.Title : null);
    }

    render() {
        return (
            <div className="cp-component-div">
                <section className="full-width listing bg-grey angle--top-right">
                    <div className="container-fluid">
                        <h2 className="sectionHead">{this.title}</h2>
                        <ProductItemList />
                    </div>
                </section>
            </div>
        )
    }
}

// Vue.js/procam/components/products.vue
<template>
  <div class="cp-component-div">
    <section class="full-width listing bg-grey angle--top-right">
      <div class="container-fluid">
        <h2 class="sectionHead">{{title}}</h2>
        <ProductItemList />
      </div>
    </section>
  </div>
</template>
<script>
import {CmsComponent, CmsField, CmsFieldTypes} from 'crownpeak-dxm-vuejs-sdk';
import ProductItemList from "./productItemList.vue";

export default {
  extends: CmsComponent,
  name: "Products",
  components: {
    ProductItemList
  },
  data() {
    return {
      title: new CmsField("Title", CmsFieldTypes.TEXT, this.$props && this.$props.data ? this.$props.data.Title : null)
    }
  }
};
</script>
