// React/procam/components/productItemList.js
import React from 'react'
import {CmsComponent, CmsDataCache, CmsField, CmsFieldTypes} from 'crownpeak-dxm-react-sdk';
import ProductItem from "./productItem";

export default class ProductItemList extends CmsComponent {
    constructor(props) {
        super(props);
        this.products = new CmsField("Products", "", CmsDataCache.get(CmsDataCache.cmsAssetId).Products.ProductItemList || []);
    }

    render() {
        let i = 0;
        return (
            <div className="row text-center">
                {/* <List name="Products" type="ProductItem"> */}
                {this.products.value.map(sc => {
                    return <ProductItem data={sc.ProductItem} key={i++}/>
                })}
                {/* </List> */}
            </div>

        )
    }
}

// Vue.js/procam/components/productItemList.vue
<template>
  <div class="row text-center">
    <!-- <List name="Products" type="ProductItem"> -->
    <ProductItem v-for="(sc, i) in products.value" :key="i" v-bind:data="sc.ProductItem" />
    <!-- </List> -->
  </div>
</template>
<script>
import {CmsComponent, CmsField, CmsDataCache} from 'crownpeak-dxm-vuejs-sdk';
import ProductItem from "../components/productItem.vue";

export default {
  extends: CmsComponent,
  name: "ProductItemList",
  props: ['data'],
  components: {
    ProductItem
  },
  data() {
    return {
      products: new CmsField("Products", "ImagePanelItem", CmsDataCache.get(CmsDataCache.cmsAssetId).Products.ProductItemList || []),
    }
  }
};
</script>
