// React/procam/components/procam/twoBluePanels.js
import React from 'react'
import {CmsComponent, CmsDataCache, CmsField} from 'crownpeak-dxm-react-sdk';
import PanelItem from "./panelItem";

export default class TwoBluePanels extends CmsComponent {
    constructor(props) {
        super(props);
        this.panels = new CmsField("Panels", "", CmsDataCache.get(CmsDataCache.cmsAssetId).TwoBluePanels.Panels || []);
    }

    render() {
        let i = 0;
        return (
            <div className="cp-component-div">
                <section className="full-width page-promos bg-blue">
                    <div className="container-fluid">
                        <div className="row">
                            {/* <List name="Panels" type="PanelItem"> */}
                            {this.panels.value.map(sc => {
                                return <PanelItem data={sc.PanelItem} key={i++}/>
                            })}
                            {/* </List> */}
                        </div>
                    </div>
                </section>
            </div>
        )
    }
}

// Vue.js/procam/components/twoBluePanels.vue
<template>
  <div class="cp-component-div">
    <section class="full-width page-promos bg-blue">
      <div class="container-fluid">
        <div class="row">
          <!-- <List name="Panels" type="PanelItem"> -->
          <PanelItem v-for="(sc, i) in panels.value" :key="i" v-bind:data="sc.PanelItem" />
          <!-- </List> -->
        </div>
      </div>
    </section>
  </div>
</template>
<script>
import {CmsComponent, CmsField, CmsDataCache} from 'crownpeak-dxm-vuejs-sdk';
import PanelItem from "./panelItem.vue";

export default {
  extends: CmsComponent,
  name: "TwoBluePanels",
  components: {PanelItem},
  data() {
    return {
      panels: new CmsField("Panels", "", CmsDataCache.get(CmsDataCache.cmsAssetId).TwoBluePanels || [])
    }
  }
};
</script>
