// Vue.js/procam/components/procam/twoBluePanels.vue
<template>
  <div class="cp-component-div">
    <section class="full-width page-promos bg-blue">
      <div class="container-fluid">
        <div class="row">
          <!-- <List name="Panels" type="PanelItem"> -->
          <PanelItem v-for="(sc, i) in panels.value" :key="i" v-bind:data="sc.PanelItem" />
          <!-- </List> -->
        </div>
      </div>
    </section>
  </div>
</template>
<script>
import {CmsComponent, CmsField, CmsDataCache} from 'crownpeak-dxm-vuejs-sdk';
import PanelItem from "./panelItem.vue";

export default {
  extends: CmsComponent,
  name: "TwoBluePanels",
  components: {PanelItem},
  data() {
    return {
      panels: new CmsField("Panels", "", CmsDataCache.get(CmsDataCache.cmsAssetId).TwoBluePanels.Panels || [])
    }
  }
};
</script>

// React/Procam-Gatsby/src/components/draggable/twoBluePanels.js
import * as React from "react"
import { CmsDataCache, CmsField, CmsFieldTypes } from 'crownpeak-dxm-react-sdk'
import PanelItem from '../raw/panelItem'

const TwoBluePanels = (props) => {
    CmsDataCache.setComponent("TwoBluePanels");
    const cmsDisableDragDrop = false;

    let panels = new CmsField("TwoBluePanels", "PanelItem", (CmsFieldTypes.TEXT, props && props.data ? props.data.Panels : CmsDataCache.get(CmsDataCache.cmsAssetId)[CmsDataCache.cmsComponentName].Panels) || []);
    let i = 0;

    return (
        <div className="cp-component-div">
            <section className="full-width page-promos bg-blue">
                <div className="container-fluid">
                    <div className="row">
                        {/* <List name="Panels" type="PanelItem"> */}
                        {panels.value.map(sc => {
                            return <PanelItem data={sc.PanelItem} key={i++} />
                        })}
                        {/* </List> */}
                    </div>
                </div>
            </section>
        </div>
    )
}

export default TwoBluePanels
