// React/procam/components/blog/blogPost.js
import React from 'react';
import { CmsComponent, CmsField, CmsFieldTypes } from 'crownpeak-dxm-react-sdk';
import ReactHtmlParser from 'react-html-parser';

export default class BlogPost extends CmsComponent
{
    constructor(props)
    {
        super(props);
        this.cmsFolder = "Blogs";
        this.cmsDisableDragDrop = true;

        this.post_title = new CmsField("Post_Title", CmsFieldTypes.TEXT);
        this.post_date = new CmsField("Post_Date", CmsFieldTypes.DATE);
        this.post_content = new CmsField("Post_Content", CmsFieldTypes.WYSIWYG);
        this.post_category = new CmsField("Post_Category", CmsFieldTypes.DOCUMENT);
    }

    render() {
        return (
            <div className="blog-post">
                <h2 className="blog-post-title">{ this.post_title }</h2>
                <p className="blog-post-meta">Date: { new Date(this.post_date).toLocaleDateString() }</p>
                { ReactHtmlParser(this.post_content) }
                { /*this.post_category*/ }
            </div>
        )
    }
}

// Vue.js/bootstrap-blog/components/blogPost.vue
<template>
    <div class="blog-post">
        <h2 class="blog-post-title">{{ post_title }}</h2>
        <p class="blog-post-meta">Date: {{ new Date(this.post_date).toLocaleDateString() }}</p>
        <span v-html="post_content"/>
        {{ /*post_category*/ }}
    </div>
</template>
<script>
    import { CmsComponent, CmsField, CmsFieldTypes } from 'crownpeak-dxm-vuejs-sdk';
    export default {
        extends: CmsComponent,
        name: "BlogPost",
        data() {
            return {
                post_title: new CmsField("Post_Title", CmsFieldTypes.TEXT, this.$props && this.$props.data ? this.$props.data.Post_Title : null),
                post_date: new CmsField("Post_Date", CmsFieldTypes.DATE, this.$props && this.$props.data ? this.$props.data.Post_Date : null),
                post_content: new CmsField("Post_Content", CmsFieldTypes.WYSIWYG, this.$props && this.$props.data ? this.$props.data.Post_Content : null),
                post_category: new CmsField("Post_Category", CmsFieldTypes.DOCUMENT, this.$props && this.$props.data ? this.$props.data.Post_Category : null)
            }
        }
    };
</script>
