// React/bootstrap-blog/components/topicList.js
import React from 'react';
import { CmsComponent, CmsStaticDataProvider } from 'crownpeak-dxm-react-sdk';

export default class TopicList extends CmsComponent
{
    constructor(props)
    {
        super (props);
        this.topics = new CmsStaticDataProvider().getCustomData("topics.json");
    }

    render() {
        return (
            <div className="nav-scroller py-1 mb-2">
                <nav className="nav d-flex justify-content-between">
                    {this.topics.map((topic) => {
                        return <a key={topic.toString()} className="p-2 text-muted" href="#">{ topic }</a>
                    })}
                </nav>
            </div>
        )
    }
}

// Vue.js/bootstrap-blog/components/topicList.vue
<template>
    <div class="nav-scroller py-1 mb-2">
        <nav class="nav d-flex justify-content-between">
            <a v-for="topic in topics" :key="topic" class="p-2 text-muted" href="#">{{ topic }}</a>
        </nav>
    </div>
</template>
<script>
    import { CmsComponent, CmsStaticDataProvider } from 'crownpeak-dxm-vuejs-sdk';
    export default {
        extends: CmsComponent,
        name: "TopicList",
        data() {
            return {
                topics: new CmsStaticDataProvider().getCustomData("topics.json")
            }
        }
    };
</script>
