// Angular/bootstrap-blog/components/topicList.ts
import {Component, Input} from '@angular/core';
import {CmsComponent, CmsStaticDataProvider} from 'crownpeak-dxm-angular-sdk';

@Component({
    selector: '[component=TopicList]',
    template: `
        <nav class="nav d-flex justify-content-between">
            <a *ngFor="let topic of topics" class="p-2 text-muted" href="#">{{ topic }}</a>
        </nav>
    `
})
export class TopicList extends CmsComponent {
    @Input() data: any;
    topics: {} = new CmsStaticDataProvider().getCustomData("topics.json");
}

// Vue.js/bootstrap-blog/components/topicList.vue
<template>
    <div class="nav-scroller py-1 mb-2">
        <nav class="nav d-flex justify-content-between">
            <a v-for="topic in topics" :key="topic" class="p-2 text-muted" href="#">{{ topic }}</a>
        </nav>
    </div>
</template>
<script>
    import { CmsComponent, CmsStaticDataProvider } from 'crownpeak-dxm-vuejs-sdk';
    export default {
        extends: CmsComponent,
        name: "TopicList",
        data() {
            return {
                topics: new CmsStaticDataProvider().getCustomData("topics.json")
            }
        }
    };
</script>
