// Vue.js/procam/components/procam/admin/headerNavigationAdmin.vue
<template>
  <div class="navbar-collapse collapse" id="navigationContent">
    <ul class="navbar-nav" role="menubar">
      <!-- <List name="NavItems" type="Link"> -->
      <li class="nav-item" v-for="(sc, i) in nav_items.value" :key="i">
        <a class="nav-link" href="{sc.Link.url}" role="menuitem">{sc.Link.title}</a>
      </li>
      <!-- </List> -->
    </ul>
  </div>
</template>
<script>
import {CmsComponent, CmsField} from 'crownpeak-dxm-vuejs-sdk';

export default {
  extends: CmsComponent,
  name: "HeaderNavigationAdmin",
  data() {
    return {
      nav_items: new CmsField("Nav_Items", "", CmsDataCache.get(CmsDataCache.cmsAssetId).Nav_Items.Links || [])
    }
  }
};
</script>

// React/procam/components/procam/admin/headerNavigationAdmin.js
import React from 'react'
import {CmsComponent, CmsDataCache, CmsField} from 'crownpeak-dxm-react-sdk';

export default class HeaderNavigationAdmin extends CmsComponent {
    constructor(props) {
        super(props);
        this.nav_items = new CmsField("Nav_Items", "", CmsDataCache.get(CmsDataCache.cmsAssetId).Nav_Items.Links || []);
    }

    render() {
        return (
            <div className="navbar-collapse collapse" id="navigationContent">
                <ul className="navbar-nav" role="menubar">
                    {/* <List name="NavItems" type="Link"> */}
                    {this.nav_items.value.map(item => {
                        return
                            <li className="nav-item" key={i++}>
                                <a className="nav-link" href="{item.NavItem.url}" role="menuitem">{item.NavItem.title}</a>
                            </li>
                    })}
                    {/* </List> */}
                </ul>
            </div>
        )
    }
}
