// Vue.js/procam/components/procam/admin/link.vue
<template>
  <li class="nav-item">
    <a class="nav-link" :href="url" role="menuitem">{title}</a>
  </li>
</template>
<script>
import {CmsComponent, CmsField, CmsFieldTypes} from 'crownpeak-dxm-vuejs-sdk';

export default {
  extends: CmsComponent,
  name: "Link",
  data() {
    return {
      title: new CmsField("Title", CmsFieldTypes.TEXT),
      url: new CmsField("Url", CmsFieldTypes.HREF)
    }
  }
};
</script>

// React/procam/components/procam/admin/link.js
import React from 'react'
import {CmsComponent, CmsField, CmsFieldTypes} from 'crownpeak-dxm-react-sdk';

export default class Link extends CmsComponent {
    constructor(props) {
        super(props);
        this.title = new CmsField("Title", CmsFieldTypes.TEXT);
        this.url = new CmsField("Url", CmsFieldTypes.HREF);
    }

    render() {
        return (
            <li class="nav-item">
                <a class="nav-link" href={this.url} role="menuitem">{this.title}</a>
            </li>
        )
    }
}
