// Vue.js/bootstrap-blog/components/blogPost.vue
<template>
    <div class="blog-post">
        <h2 class="blog-post-title">{{ post_title }}</h2>
        <p class="blog-post-meta">Date: {{ new Date(this.post_date).toLocaleDateString() }}</p>
        <span v-html="post_content"/>
        {{ /*post_category*/ }}
    </div>
</template>
<script>
    import { CmsComponent, CmsField, CmsFieldTypes } from 'crownpeak-dxm-vuejs-sdk';
    export default {
        extends: CmsComponent,
        name: "BlogPost",
        data() {
            return {
                post_title: new CmsField("Post_Title", CmsFieldTypes.TEXT, this.$props && this.$props.data ? this.$props.data.Post_Title : null),
                post_date: new CmsField("Post_Date", CmsFieldTypes.DATE, this.$props && this.$props.data ? this.$props.data.Post_Date : null),
                post_content: new CmsField("Post_Content", CmsFieldTypes.WYSIWYG, this.$props && this.$props.data ? this.$props.data.Post_Content : null),
                post_category: new CmsField("Post_Category", CmsFieldTypes.DOCUMENT, this.$props && this.$props.data ? this.$props.data.Post_Category : null)
            }
        }
    };
</script>

// Angular/bootstrap-blog/components/blogPost.ts
import {Component, Input} from '@angular/core';
import { CmsComponent, CmsField, CmsFieldTypes } from 'crownpeak-dxm-angular-sdk';

@Component({
    selector: '[component=BlogPost]',
    template: `
        <div class="blog-post">
            <h2 class="blog-post-title">{{ post_title }}</h2>
            <p class="blog-post-meta">Date: <!--{{ post_date | date:'longdate' }}--></p>
            <p [innerHTML]="post_content"></p>
            <!-- {{ /*post_category*/ }} -->
        </div>
    `
})
export class BlogPost extends CmsComponent {
    @Input() data:any;
    post_title: CmsField = new CmsField("Post_Title", CmsFieldTypes.TEXT, null);
    post_date: CmsField = new CmsField("Post_Date", CmsFieldTypes.DATE, null);
    post_content: CmsField = new CmsField("Post_Content", CmsFieldTypes.WYSIWYG, null);
    post_category: CmsField = new CmsField("Post_Category", CmsFieldTypes.DOCUMENT, null);
}
